# Google Cloud Build configuration for easyMO-Discovery
# Builds Docker image and deploys to Cloud Run

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/easymo-discovery:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/easymo-discovery:latest'
      - '.'

  # Step 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/easymo-discovery:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/easymo-discovery:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'easymo-discovery'
      - '--image'
      - 'gcr.io/$PROJECT_ID/easymo-discovery:$COMMIT_SHA'
      - '--region'
      - '${_DEPLOY_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/easymo-discovery:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/easymo-discovery:latest'

# Substitution variables
substitutions:
  _DEPLOY_REGION: europe-west1

# Timeout for the entire build
timeout: '1200s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
