/**
 * Demo component for ChatKit widgets
 * 
 * This file demonstrates how to use the widget pack by generating
 * sample widget objects and printing them as JSON.
 * 
 * Usage:
 *   npx tsx packages/chatkit-widget-pack/demo.ts
 * 
 * Note: This is a development/demo tool. In production, widgets
 * are generated by your agent and rendered by ChatKit.
 */

import {
  ModePickerCard,
  PassengerRideRequestCard,
  MarketplaceSearchCard,
  BroadcastComposerCard,
  BroadcastTargetsPreviewCard,
  BroadcastProgressCard,
  IncomingResponsesCard,
} from "./src/index";

console.log("=== ChatKit Widget Pack Demo ===\n");

console.log("1. Mode Picker Card:");
console.log(JSON.stringify(ModePickerCard(), null, 2));
console.log("\n");

console.log("2. Passenger Ride Request Card:");
console.log(JSON.stringify(PassengerRideRequestCard(), null, 2));
console.log("\n");

console.log("3. Marketplace Search Card:");
console.log(JSON.stringify(MarketplaceSearchCard(), null, 2));
console.log("\n");

console.log("4. Broadcast Composer Card:");
console.log(JSON.stringify(BroadcastComposerCard(), null, 2));
console.log("\n");

console.log("5. Broadcast Targets Preview Card (sample):");
console.log(
  JSON.stringify(
    BroadcastTargetsPreviewCard(
      [
        { business_id: "1", name: "Pharmacy ABC", category: "pharmacy", distance_km: 0.5, status: "pending" },
        { business_id: "2", name: "Pharmacy XYZ", category: "pharmacy", distance_km: 1.2, status: "pending" },
      ],
      { campaign_id: "demo-123", need: "paracetamol", radius_km: 3, max_targets: 15 }
    ),
    null,
    2
  )
);
console.log("\n");

console.log("6. Broadcast Progress Card (sample):");
console.log(
  JSON.stringify(
    BroadcastProgressCard(
      { campaign_id: "demo-123", total: 15, sent: 15, delivered: 12, replied: 3, failed: 0 },
      [
        { business_id: "1", name: "Pharmacy ABC", status: "replied" },
        { business_id: "2", name: "Pharmacy XYZ", status: "delivered" },
      ]
    ),
    null,
    2
  )
);
console.log("\n");

console.log("7. Incoming Responses Card (sample):");
console.log(
  JSON.stringify(
    IncomingResponsesCard("demo-123", [
      { business_name: "Pharmacy ABC", text: "Yes, we have paracetamol in stock", ts: "2025-01-27T10:00:00Z", business_id: "1" },
      { business_name: "Pharmacy XYZ", text: "Available, price is 2000 RWF", ts: "2025-01-27T10:05:00Z", business_id: "2" },
    ]),
    null,
    2
  )
);
console.log("\n");

console.log("=== Demo Complete ===");
console.log("\nTo use these widgets in your agent:");
console.log("1. Import the widget functions in your agent code");
console.log("2. Return the widget object from your agent's response");
console.log("3. ChatKit will render the widget in the UI");
console.log("4. User interactions trigger actions that your agent handles");

