#!/usr/bin/env node
/**
 * generate-env.mjs
 * 
 * Post-build script that generates env.js with runtime configuration.
 * This allows Cloudflare Pages to inject environment variables at deploy time,
 * providing a fallback for cases where Vite's build-time injection fails.
 * 
 * Usage: node scripts/generate-env.mjs
 * 
 * Output: apps/pwa/dist/env.js
 */

import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Public environment variables to include in env.js
// IMPORTANT: Only include PUBLIC client-safe variables here - no secrets!
const PUBLIC_VARS = [
    'VITE_SUPABASE_URL',
    'VITE_SUPABASE_ANON_KEY',
];

function main() {
    console.log('\n📦 Generating runtime environment config (env.js)...\n');

    // Build the config object
    const config = {};
    PUBLIC_VARS.forEach((varName) => {
        const value = process.env[varName];
        if (value) {
            config[varName] = value;
        }
    });

    // Generate the JavaScript content
    const content = `// Auto-generated by generate-env.mjs at build time
// This file provides runtime environment configuration for Cloudflare Pages
window.__APP_ENV__ = ${JSON.stringify(config, null, 2)};
`;

    // Determine output path (apps/pwa/dist/env.js)
    const distPath = resolve(__dirname, '..', 'apps', 'pwa', 'dist');
    const outputPath = resolve(distPath, 'env.js');

    // Ensure dist directory exists
    if (!existsSync(distPath)) {
        console.log(`  Creating directory: ${distPath}`);
        mkdirSync(distPath, { recursive: true });
    }

    // Write the file
    writeFileSync(outputPath, content, 'utf-8');

    console.log(`  ✅ Created: ${outputPath}`);
    console.log('\n  Contents:');
    console.log('  ' + '-'.repeat(50));
    content.split('\n').forEach((line) => {
        console.log(`  ${line}`);
    });
    console.log('  ' + '-'.repeat(50));
    console.log('\n✅ env.js generated successfully!\n');
}

main();
